Unit test to include/exclude news sources
bdfinlayson/headline_grabber pull request #12
Opened 2024-07-06 17:50 UTC by Sheena309

Added a test file: test_filter_sites.py

2024-07-08 18:13 UTC, bdfinlayson requested changes
remove all print statements and commented code

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    print(f"Total number of YAML files: {total_sites}")
let's remove these print statements

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    print(f"Expected sites length: {len(expected_abbreviations)}")
remove

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    print("***test_include_option passed***")
remove

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    print(f"Total number of YAML files: {total_sites}")
remove

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    print("***test_exclude_option passed***")
remove

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    print(f"Expected length of YAML files: {expected_length}")
remove

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +'''
remove commented code

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    print("***test_include_and_exclude_option passed***")
remove

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    '''
remove commented code

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    #user_input = UserPreferences(include=["nyt"])
remove comment

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    # Print the number of YAML files loaded
remove comment

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    return sites
use the `copy()` method on this for safety

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    # Print the number of YAML files loaded
remove comment

2024-07-08 18:13 UTC, bdfinlayson commented on tests/test_filter_sites.py
> +    #result_context = filter_sites.run(context)
remove commented code

2024-07-08 18:13 UTC, bdfinlayson requested changes

2024-07-08 18:13 UTC, bdfinlayson commented on src/headline_grabber/pipeline_steps/filter_sites.py
> +
remove extra line

2024-07-09 23:27 UTC, bdfinlayson approved these changes
looking good thanks @Sheena309

2024-07-09 23:31 UTC, tonthattuit commented
@Sheena309

2024-07-10 21:03 UTC, tonthattuit approved these changes
Looks good to me. Approved.

2024-07-10 21:03 UTC, merged