Feature/hg18 unittest parsing html from wap
bdfinlayson/headline_grabber pull request #16
Opened 2024-07-09 03:31 UTC by Sheena309

2024-07-09 14:20 UTC, bdfinlayson requested changes
@Sheena309 once you've resolved comments on feature/HG21-add-progress-bars please pull those changes into this branch, since it looks like you've branched off of that one to create this one

2024-07-09 15:01 UTC, bdfinlayson requested changes

2024-07-09 15:01 UTC, bdfinlayson commented on tests/headline_grabber/pipeline_steps/test_scrape_text_wap.py
> +    actualResult = scrape_text.run(pipeline_context)
you shouldn't be running the entire step unless you plan to mock the html requests, which you're not. Either mock the html requests, or pass in a stub html string to the get headlines beautifulsoup method

2024-07-09 21:17 UTC, Sheena309 commented
> @Sheena309 once you've resolved comments on feature/HG21-add-progress-bars please pull those changes into this branch, since it looks like you've branched off of that one to create this one

Done!

2024-07-11 16:52 UTC, bdfinlayson approved these changes

2024-07-11 16:53 UTC, bdfinlayson approved these changes

2024-07-11 16:55 UTC, bdfinlayson approved these changes

2024-07-11 16:58 UTC, bdfinlayson approved these changes
LGTM

2024-07-11 16:59 UTC, bdfinlayson submitted a review, later dismissed

2024-07-11 17:06 UTC, tonthattuit approved these changes
Looks good to me. Approved!

2024-07-11 17:08 UTC, tonthattuit approved these changes

2024-07-11 17:18 UTC, merged